version: "3"

services:
  app:
    container_name: app1
    image: ubuntu:21.10
    volumes:
      - ../src:/src:ro
    command: /src/main.sh
    env_file:
      - ./app.env
    secrets:
      - SECRET1

secrets:
  SECRET1:
    external: true
